spring:
  cloud:
    openfeign:
      client:
        config:
          users:
            url: https://api.mercadolibre.com
            
  threads:
    virtual:
      enabled: true
compare:
  products:
    api:
      version: 4