spring:
  application:
    name: servicio-vendedores
  cloud:
    openfeign:
      client:
        config:
          users:
            url: ${compare.products.paths.api}
    bus:
      enabled: true
      refresh:
        enabled: true
  threads:
    virtual:
      enabled: true
server:
  port: 0
  
management:
  security:
    enabled: false   
  endpoints:
    web:
      exposure:
        include: "*"

  