spring:
  application:
    name: servicio-vendedores
  cloud:
    openfeign:
      client:
        config:
          users:
            url: ${compare.products.paths.api}
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 0
  

  