spring:
  application:
    name: servicio-vendedores
  cloud:
    openfeign:
      client:
        config:
          users:
            url: https://api.mercadolibre.com
            
  threads:
    virtual:
      enabled: true
server:
  port: 0