spring:
  application:
    name: servicio-comparacion-publicaciones
  threads:
    virtual:
      enabled: true
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
server:
  port: 9090
  
management:
  security:
    enabled: false   
  endpoints:
    web:
      exposure:
        include: "*"