server:
  port: 9090
spring:
  application:
    name: servicio-analisis-categoria
  threads:
    virtual:
      enabled: true     
  
compare:
  products:
    paths:
     info-category: https://api.mercadolibre.com/categories/{id}

responses:
  json-property:
    father-category: path_from_root

categories:
  end-code:
    service: '1540'
    vehicle: '1743'
    property: '1459'
