server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #url del repositorio git donde se encuentran los archivos de propiedades
          uri: https://github.com/MateoRodriguez0/mercadolibre-products-comparator-config.git
          # evitamos validacion de certificado ssl al utilizar el protocolo https
          skip-ssl-validation: true
          #tiempo de espera para conectarse al repositorio remoto(en segundos)
          timeout: 10
          
          #autenticacion
          username: MateoRodriguez0
          password: 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
          #frecuencia con la que se actualizará el servidor
          refresh-rate: 0          
          #rama del repositorio por defecto
          default-label: main
          
  security:
    user:
      name: config
      password: config
   
  devtools:
    livereload:
      port: 10002
#Registramos el este de configuracion en eureka server
eureka:
  client:
    service-url:
      defaultZone: http://eurekaclient:eurekaclient@localhost:8761/eureka/
  #nombre con el que se registará el servicio    
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    #metadatos del servicio (incluimos las credenciales del usuario)
    metadata-map:
      user: ${spring.security.user.name}
      password: ${spring.security.user.password}

  