spring:
  application:
    name: servicio-productos-opiniones                       
  threads:
    virtual:
      enabled: true 
  cloud:
    openfeign:
      client:
        config:
          ReviewsClient:
           url: ${compare.products.api}
    bus:
      enabled: true
      refresh:
        enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    
server: 
  port: ${PORT:8080}
 
management:
  security:
    enabled: false   
  endpoints:
    web:
      exposure:
        include: "*"  
        
