spring:
  application:
    name: servicio-productos-opiniones                       
  threads:
    virtual:
      enabled: true 
  cloud:
    openfeign:
      client:
        config:
          ReviewsClient:
           url: ${compare.products.api}
    bus:
      enabled: true
      refresh:
        enabled: true
  
server: 
  port: 8080
 
management:
  security:
    enabled: false   
  endpoints:
    web:
      exposure:
        include: "*"