spring:
  application:
    name: servicio-productos-opiniones                       
  threads:
    virtual:
      enabled: true 
  cloud:
    openfeign:
      client:
        config:
          ReviewsClient:
           url: ${compare.products.api}
    
server: 
  port: 0