spring: 
  threads:
    virtual:
      enabled: true
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
server:
  port: 9097
 
management:
  security:
    enabled: false   
  endpoints:
    web:
      exposure:
        include: "*"