spring:
  application:
    name: servicio-productos-comparacion-caracteristicas
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 9093 
    